# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# Auto Update Enable
DISABLE_AUTO_UPDATE="true"
# Default Theme
ZSH_THEME="robbyrussell"
# Active plugins
plugins=(git themes pip node npm history-substring-search zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

export PATH=~/.npm-global/bin:$PATH

# export LC_TYPE="en_US.UTF-8"
# export LC_ALL="en_US.UTF-8"
