# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# define where custom plugins live:
ZSH_CUSTOM=~/.oh-my-zsh/custom/
# Auto Update Enable
DISABLE_UPDATE_PROMPT=true

ZSH_THEME="robbyrussell"

plugins=(git archlinux django sublime themes python pip node npm history-substring-search zsh-syntax-highlighting vagrant)

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export PATH=~/.npm-global/bin:$PATH

# export LC_TYPE="en_US.UTF-8"
# export LC_ALL="en_US.UTF-8"
